# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
# cyberdream theme for lazygit
gui:
  border: rounded
  theme:
    activeBorderColor:
      - "#5ef1ff"
      - bold
    inactiveBorderColor:
      - "#7b8496"
    searchingActiveBorderColor:
      - "#ff5ef1"
    optionsTextColor:
      - "#ffffff"
    selectedLineBgColor:
      - "#3c4048"
    cherryPickedCommitBgColor:
      - "#3c4048"
    cherryPickedCommitFgColor:
      - "#ff5ea0"
    unstagedChangesColor:
      - "#ffbd5e"
    defaultFgColor:
      - "#ffffff"

